version: '3.7'

services:

  lfi-basic:
    build: ./LFI/basic/
    ports:
      - "3000:2776"

  exporting-data-on-inspector-gadget:
    build: ./LFI/exporting data on inspector gadget/
    ports:
      - "3001:2776"

  sqli:
    build: ./SQLi/basic
    ports:
      - "3002:2776"

  rxss:
    container_name: rxss
    build: ./XSS/reflection
    ports:
      - "3003:2776"

  sxss-admin:
    container_name: sxss-admin
    build: ./XSS/getting the admin
    ports:
      - "3004:2776"
  
  sxss-staff:
    container_name: sxss-staff
    build: ./XSS/getting the staff cookies
    ports:
      - "3005:2776"

  os-cmd-inj:
    build: ./OS Cmd Inj/basic
    read_only: true
    tmpfs: /tmp
    ports:
      - "3006:2776"

  safe-cmd:
    build: ./OS Cmd Inj/safe cmd
    read_only: true
    tmpfs: /tmp
    ports:
      - "3007:2776"

  worker-union:
    build: ./SQLi/Worker's Union
    read_only: true
    tmpfs: /tmp
    ports:
      - "3008:2776"